name: "develop - DESTROY infra"

on:
  workflow_dispatch:
    branches:
      - develop

env:
  # Possible values: https://developer.hashicorp.com/terraform/internals/debugging
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for the Terraform state
  S3_BUCKET_TF_STATE: "develop-test-llm-terraform-state"
  TF_STATE_FILE: "vpc-eks.tfstate"
  AWS_REGION: "us-east-1"
  TERRAFORM_VERSION: "1.7.0"
  ENVIRONMENT: develop
  EKS_CLUSTER_NAME: develop-eks-cluster
  TEST_NAMESPACE: "demo-test"

jobs:
  # Destroy S3 bucket with Crossplane
  destroy_s3bucket:
    name: "Destroy S3 bucket"
    runs-on: ubuntu-latest
    #environment: $ENVIRONMENT
    defaults:
      run:
        working-directory: crossplane
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME

      - name: "Deploy S3 bucket"
        run: kubectl delete -f s3bucket.yaml

  destroy_monitoring:
    name: "Delete Prometheus and Grafana"
    runs-on: ubuntu-latest
    #environment: $ENVIRONMENT
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      # Destroy monitoring
      - name: Destroy monitoring
        run: |
          helm -n monitoring uninstall mon
      # Delete the monitoring namespace
      - name: Destroy monitoring namespace
        run: |
          kubectl delete namespace monitoring


  destroy_public_lb_aws_parameterstore:
    name: "Delete AWS ParameterStore with the public AWS LB dns name"
    runs-on: ubuntu-latest
    #environment: $ENVIRONMENT
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Delete Parameter from AWS Parameter Store
        run: |
          aws ssm delete-parameter --name "/$ENVIRONMENT/ingress-public-load-balancer-dns"

  destroy_public_ingress:
    name: "Delete public nginx ingress controller"
    runs-on: ubuntu-latest
    #environment: $ENVIRONMENT
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - name: Destroy public ingress controller
        run: |
          helm -n public-ingress uninstall public-ingress


  destroy_eks_and_vpc:
    name: "Delete the EKS cluster and VPC"
    runs-on: ubuntu-latest
    #environment: $ENVIRONMENT
    needs: [destroy_s3bucket, destroy_public_ingress, destroy_public_lb_aws_parameterstore, destroy_monitoring]
    defaults:
      run:
        working-directory: terraform-code/vpc-eks
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: $TERRAFORM_VERSION

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config "bucket=$S3_BUCKET_TF_STATE" \
            -backend-config "key=$TF_STATE_FILE"

      - name: Fetch Variables File
        uses: actions/checkout@v2
        with:
          repository: luisllm/environments
          ref: develop  # or specify the branch, tag, or commit hash where the file resides
          path: './environments'
            
      - name: Terraform Destroy
        run: terraform destroy -var-file="../../environments/tf-config/infra.tfvars" -auto-approve